server:
  port: 7090
  servlet:
    context-path: /api
    session:
      timeout: PT60M
# database
spring:
  datasource:
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/easy_space?characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: smtp.163.com
    port: 465
    username: dy_zxp@163.com
    password: Zhuang098
    default-encoding: UTF-8

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl